- name: psycopg2 dependencies
  become: yes
  apt:
    name:
      - python3-dev
      - libpq-dev
      - python3-pip

- name: install psycopg2
  become: yes
  ansible.builtin.pip:
    name: psycopg2

- name: ensure database is created {{app_db_name}}
  become: yes
  postgresql_db:
    db: "{{app_db_name}}"

- name: ensure user has access to database
  become: yes
  postgresql_user:
    db: "{{app_db_name}}"
    user: "{{app_db_user}}"
    password: "{{app_db_password}}"
    priv: ALL

- name: ensure new user does not have unnecessary privileges
  become: yes
  postgresql_user:
    user: "{{app_db_user}}"
    role_attr_flags: NOSUPERUSER
