- name: upload backup file
  copy:
    src: "{{dbrestoredump}}"
    dest: /home/{{deploy_user}}/dbrestoredump.sql.gz
  when: dbrestoredump != ""

- name: restore database from dump
  postgresql_db:
    db: "{{dbname}}"
    login_user: "{{dbuser}}"
    login_password: "{{dbpassword}}"
    state: restore
    target: /home/{{deploy_user}}/dbrestoredump.sql.gz
  when: dbrestoredump != ""
