- name: upload backup file
  copy:
    src: "{{db_restoredump}}"
    dest: /home/{{ansible_user}}/dbrestoredump.sql.gz
  when: dbrestoredump != ""

- name: restore database from dump
  postgresql_db:
    db: "{{app_db_name}}"
    login_user: "{{app_db_user}}"
    login_password: "{{app_db_password}}"
    state: restore
    target: /home/{{ansible_user}}/dbrestoredump.sql.gz
  when: dbrestoredump != ""
