- name: Pull official registry image
  docker_image:
    name: registry:2
    source: pull

# https://github.com/docker/docs/blob/master/registry/storage-drivers/s3.md
- name: Make registry to run at startup
  docker_container:
    image: registry:2
    name: docker_registry
    env:
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_REGION: "{{aws_s3_docker_registry_region}}"
      REGISTRY_STORAGE_S3_BUCKET: "{{aws_s3_docker_registry_bucket}}"
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: "inmemory"
      REGISTRY_STORAGE_S3_ACCESSKEY: "{{aws_s3_docker_registry_key}}"
      REGISTRY_STORAGE_S3_SECRETKEY: "{{aws_s3_docker_registry_secret}}"
      REGISTRY_HTTP_SECRET: "{{aws_s3_docker_registry_http_secret}}"
    published_ports:
      - 127.0.0.1:5000:5000
    restart_policy: unless-stopped

