- name: "Check that we have a docker port for the new deployment {{app_docker_port}} <-"
  ansible.builtin.shell: "false"
  when: not app_docker_port.stdout

- name: "NGINX write configuration for {{ app_name }} @ {{ app_domain }}:"
  become: yes
  when: app_ssl == true
  template:
    src: nginx_ssl_letsencrypt.conf.j2
    dest: "/etc/nginx/conf.d/{{app_name}}_{{app_name}}.conf"
  notify:
    - restart nginx

- include: letsencrypt.yml
  when: app_ssl == true

- name: "NGINX write configuration for {{ app_name }} @ {{ app_domain }}:"
  become: yes
  when: app_ssl == false
  template:
    src: nginx_no_ssl.conf.j2
    dest: "/etc/nginx/conf.d/{{app_domain}}.conf"
  notify:
    - restart nginx

- name: "Create static files directory"
  become: yes
  ansible.builtin.file:
    path: "/var/www/static"
    group: "{{ansible_user}}"
    owner: "{{ansible_user}}"
    mode: 0777
    state: directory

- name: "Upload static files"
  ansible.builtin.copy:
    src: "{{app_source_static_files}}"
    dest: "/var/www/static/{{app_domain}}/{{app_release}}"
