- name: Install redis
  become: yes
  apt:
    name:
      - redis-server

- name: Enable bind to docker interface
  become: yes
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"

- name: Start redis unit after docker unit
  become: yes
  shell: sed -i 's/After=network.target/After=docker.service/g' /lib/systemd/system/redis-server\@.service

